version: '2.3'

services:
  spark:
    image: registry.zilliz.com/arctern/arctern-spark-gpu:v0.1.0-ubuntu18.04
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    ports:
      - '8080:8080'
      - '7077:7077'
  spark-worker-1:
    image: registry.zilliz.com/arctern/arctern-spark-gpu:v0.1.0-ubuntu18.04
    runtime: nvidia
    depends_on:
      - spark
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: registry.zilliz.com/arctern/arctern-spark-gpu:v0.1.0-ubuntu18.04
    runtime: nvidia
    depends_on:
      - spark
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
