version: '2.3'

services:
  regression:
    image: ${ARCTERN_REPO}:${ARCTERN_TAG}
    volumes:
      - ../..:/arctern
    command: &spark-test
      ["/arctern/ci/scripts/run_spark_regression.sh", "--master spark://spark-master:7077", "--conda_env=arctern", "/arctern/tests/spark_test.py"]
networks:
  default:
    external:
      name: ${ARCTERN_NETWORK}